/**
 * model.h - Auto-generated zero-dependency decision tree for ESP32 edge NIDS.
 *
 * Generated by analyze_and_train.py via m2cgen.
 * Feature order MUST match nids_features.WINDOW_FEATURES / firmware fill order.
 * DO NOT edit by hand — regenerate with: python analyze_and_train.py
 *
 * Generated: 2026-08-06T13:07:31
 */
#ifndef NIDS_MODEL_H
#define NIDS_MODEL_H

#include <string.h>  /* memcpy used by m2cgen tree */

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    double total_packets;
    double packet_density;
    double beacon_packets;
    double deauth_packets;
    double deauth_targeted;
    double probe_packets;
    double auth_packets;
    double seq_jump;
    double rssi_mean;
    double rssi_var;
    double snr_mean;
    double heap;
    double minheap;
    double reconn;
    double qpeak;
    double udpfail;
    double backlog;
} nids_window_features_t;


static inline int nids_predict(const nids_window_features_t *f)
{
    double input[17];
    double output[2];
    input[0] = f->total_packets;
    input[1] = f->packet_density;
    input[2] = f->beacon_packets;
    input[3] = f->deauth_packets;
    input[4] = f->deauth_targeted;
    input[5] = f->probe_packets;
    input[6] = f->auth_packets;
    input[7] = f->seq_jump;
    input[8] = f->rssi_mean;
    input[9] = f->rssi_var;
    input[10] = f->snr_mean;
    input[11] = f->heap;
    input[12] = f->minheap;
    input[13] = f->reconn;
    input[14] = f->qpeak;
    input[15] = f->udpfail;
    input[16] = f->backlog;
    /* --- m2cgen-generated tree --- */

    double var0[2];
    if (input[11] <= 69784.0) {
        if (input[11] <= 68124.0) {
            if (input[11] <= 65842.0) {
                if (input[11] <= 65806.0) {
                    memcpy(var0, (double[]){0.8608666180533436, 0.1391333819466563}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.20772051334284022, 0.7922794866571599}, 2 * sizeof(double));
                }
            } else {
                if (input[11] <= 65908.0) {
                    memcpy(var0, (double[]){0.9922251676837405, 0.007774832316259522}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.2800658978583195, 0.7199341021416805}, 2 * sizeof(double));
                }
            }
        } else {
            if (input[10] <= 19.5) {
                if (input[11] <= 69764.0) {
                    memcpy(var0, (double[]){0.13648269840540408, 0.8635173015945959}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.6749721085905541, 0.3250278914094459}, 2 * sizeof(double));
                }
            } else {
                if (input[3] <= 0.5) {
                    memcpy(var0, (double[]){0.06460622830144369, 0.9353937716985563}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.0, 1.0}, 2 * sizeof(double));
                }
            }
        }
    } else {
        if (input[10] <= 10.75) {
            if (input[10] <= -2.5) {
                if (input[8] <= -93.5) {
                    memcpy(var0, (double[]){0.7486579754601228, 0.2513420245398773}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.5374155199088022, 0.4625844800911978}, 2 * sizeof(double));
                }
            } else {
                if (input[8] <= -80.5) {
                    memcpy(var0, (double[]){0.842102886048507, 0.15789711395149295}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.6937631394533987, 0.30623686054660126}, 2 * sizeof(double));
                }
            }
        } else {
            if (input[10] <= 24.75) {
                if (input[10] <= 19.25) {
                    memcpy(var0, (double[]){0.47810168960588956, 0.5218983103941103}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.7199316385387732, 0.2800683614612269}, 2 * sizeof(double));
                }
            } else {
                if (input[8] <= -64.25) {
                    memcpy(var0, (double[]){0.16338790599419054, 0.8366120940058095}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.5465812494645558, 0.4534187505354442}, 2 * sizeof(double));
                }
            }
        }
    }
    memcpy(output, var0, 2 * sizeof(double));

    /* class 1 = attack */
    return (output[1] > output[0]) ? 1 : 0;
}


#ifdef __cplusplus
}
#endif

#endif /* NIDS_MODEL_H */
