/**
 * model.h - Auto-generated zero-dependency decision tree for ESP32 edge NIDS.
 *
 * Generated by analyze_and_train.py via m2cgen.
 * Feature order MUST match nids_features.WINDOW_FEATURES / firmware fill order.
 * DO NOT edit by hand — regenerate with: python analyze_and_train.py
 *
 * Generated: 2026-08-02T20:42:25
 */
#ifndef NIDS_MODEL_H
#define NIDS_MODEL_H

#include <string.h>  /* memcpy used by m2cgen tree */

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    double total_packets;
    double packet_density;
    double beacon_packets;
    double deauth_packets;
    double deauth_targeted;
    double probe_packets;
    double auth_packets;
    double seq_jump;
    double rssi_mean;
    double rssi_var;
    double snr_mean;
    double heap;
    double minheap;
    double reconn;
    double qpeak;
    double udpfail;
    double backlog;
} nids_window_features_t;


static inline int nids_predict(const nids_window_features_t *f)
{
    double input[17];
    double output[2];
    input[0] = f->total_packets;
    input[1] = f->packet_density;
    input[2] = f->beacon_packets;
    input[3] = f->deauth_packets;
    input[4] = f->deauth_targeted;
    input[5] = f->probe_packets;
    input[6] = f->auth_packets;
    input[7] = f->seq_jump;
    input[8] = f->rssi_mean;
    input[9] = f->rssi_var;
    input[10] = f->snr_mean;
    input[11] = f->heap;
    input[12] = f->minheap;
    input[13] = f->reconn;
    input[14] = f->qpeak;
    input[15] = f->udpfail;
    input[16] = f->backlog;
    /* --- m2cgen-generated tree --- */

    double var0[2];
    if (input[11] <= 74306.0) {
        if (input[8] <= -81.5) {
            memcpy(var0, (double[]){0.0, 1.0}, 2 * sizeof(double));
        } else {
            memcpy(var0, (double[]){0.0, 1.0}, 2 * sizeof(double));
        }
    } else {
        if (input[12] <= 47588.0) {
            if (input[11] <= 74734.0) {
                if (input[11] <= 74694.0) {
                    memcpy(var0, (double[]){0.9790629128976522, 0.020937087102347797}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.8180613822035769, 0.18193861779642304}, 2 * sizeof(double));
                }
            } else {
                if (input[8] <= -65.5) {
                    memcpy(var0, (double[]){0.9658269545228333, 0.03417304547716666}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.9890885207000296, 0.010911479299970342}, 2 * sizeof(double));
                }
            }
        } else {
            if (input[12] <= 60886.0) {
                memcpy(var0, (double[]){0.0, 1.0}, 2 * sizeof(double));
            } else {
                if (input[1] <= 35.0) {
                    memcpy(var0, (double[]){0.9618023363619507, 0.03819766363804933}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.0, 1.0}, 2 * sizeof(double));
                }
            }
        }
    }
    memcpy(output, var0, 2 * sizeof(double));

    /* class 1 = attack */
    return (output[1] > output[0]) ? 1 : 0;
}


#ifdef __cplusplus
}
#endif

#endif /* NIDS_MODEL_H */
