/**
 * model.h - Auto-generated zero-dependency decision tree for ESP32 edge NIDS.
 *
 * Generated by analyze_and_train.py via m2cgen.
 * Feature order MUST match nids_features.WINDOW_FEATURES / firmware fill order.
 * DO NOT edit by hand — regenerate with: python analyze_and_train.py
 *
 * Generated: 2026-08-03T00:28:32
 */
#ifndef NIDS_MODEL_H
#define NIDS_MODEL_H

#include <string.h>  /* memcpy used by m2cgen tree */

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    double total_packets;
    double packet_density;
    double beacon_packets;
    double deauth_packets;
    double deauth_targeted;
    double probe_packets;
    double auth_packets;
    double seq_jump;
    double rssi_mean;
    double rssi_var;
    double snr_mean;
    double heap;
    double minheap;
    double reconn;
    double qpeak;
    double udpfail;
    double backlog;
} nids_window_features_t;


static inline int nids_predict(const nids_window_features_t *f)
{
    double input[17];
    double output[2];
    input[0] = f->total_packets;
    input[1] = f->packet_density;
    input[2] = f->beacon_packets;
    input[3] = f->deauth_packets;
    input[4] = f->deauth_targeted;
    input[5] = f->probe_packets;
    input[6] = f->auth_packets;
    input[7] = f->seq_jump;
    input[8] = f->rssi_mean;
    input[9] = f->rssi_var;
    input[10] = f->snr_mean;
    input[11] = f->heap;
    input[12] = f->minheap;
    input[13] = f->reconn;
    input[14] = f->qpeak;
    input[15] = f->udpfail;
    input[16] = f->backlog;
    /* --- m2cgen-generated tree --- */

    double var0[2];
    if (input[11] <= 69810.0) {
        if (input[11] <= 65802.0) {
            if (input[11] <= 65796.0) {
                if (input[11] <= 65746.0) {
                    memcpy(var0, (double[]){0.1150012377258849, 0.884998762274115}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.5132226144320352, 0.4867773855679648}, 2 * sizeof(double));
                }
            } else {
                memcpy(var0, (double[]){1.0, 0.0}, 2 * sizeof(double));
            }
        } else {
            if (input[11] <= 69688.0) {
                if (input[12] <= 44540.0) {
                    memcpy(var0, (double[]){0.11622772492019666, 0.8837722750798034}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.013032783828855952, 0.986967216171144}, 2 * sizeof(double));
                }
            } else {
                if (input[14] <= 95.0) {
                    memcpy(var0, (double[]){0.13090195268106206, 0.8690980473189379}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.9353142013472363, 0.06468579865276367}, 2 * sizeof(double));
                }
            }
        }
    } else {
        if (input[11] <= 69872.0) {
            if (input[3] <= 0.5) {
                if (input[10] <= -0.5) {
                    memcpy(var0, (double[]){0.4356398279144267, 0.5643601720855733}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.6055892563044362, 0.3944107436955637}, 2 * sizeof(double));
                }
            } else {
                if (input[8] <= -86.5) {
                    memcpy(var0, (double[]){1.0, 0.0}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.011453314410204017, 0.988546685589796}, 2 * sizeof(double));
                }
            }
        } else {
            if (input[9] <= 4.25) {
                if (input[8] <= -86.5) {
                    memcpy(var0, (double[]){0.8872984211587605, 0.1127015788412395}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.7872749342504539, 0.2127250657495461}, 2 * sizeof(double));
                }
            } else {
                if (input[11] <= 69894.0) {
                    memcpy(var0, (double[]){0.7067354622786223, 0.2932645377213778}, 2 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.09124954987396472, 0.9087504501260354}, 2 * sizeof(double));
                }
            }
        }
    }
    memcpy(output, var0, 2 * sizeof(double));

    /* class 1 = attack */
    return (output[1] > output[0]) ? 1 : 0;
}


#ifdef __cplusplus
}
#endif

#endif /* NIDS_MODEL_H */
